---
title: Koren.dev
description: Lorem ipsum dolorem
#url: https://koren.dev
baseurl: 
lang: en
permalink: "/:title/"

remote_theme: korenmiklos/remote-theme

website: courses # options: blog | courses | publications

google_analytics: 

markdown: kramdown
highlighter: rouge

plugins:
- jekyll-seo-tag
- jekyll-remote-theme

exclude:
- vendor
- ".bundle"
- ".sass-cache"
- config
- Gemfile
- Gemfile.lock
- node_modules
- log
- tmp
- Rakefile
- package.json
- CHANGELOG
- LICENSE
- README
- "/docs"

livereload: true

collections:
  publications:
    output: false
  courses:
    output: true
    permalink: /:collection/:name
  posts:
    output: false
  software:
    output: false
  events:
    output: true
    permalink: /:collection/:name
  datasets:
    output: true
    permalink: /:collection/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: publication
  - scope:
      path: ""
      type: courses
    values:
      layout: course
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: events
    values:
      layout: event
  - scope:
      path: ""
      type: datasets
    values:
      layout: dataset
